Repository dreipol/multiplatform-redux-sample, pull requests merged in 2021-03, with the labels that each got.

#60 [snooze_notification] Swiftlint autocorrect
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample.xcodeproj/project.pbxproj
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/MainCoordinator.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/SettingsViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Notifications/NotificationManager.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Notifications/SnoozeNotifcation+UserNotifications.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/OnboardingCardViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/ToggleListItem.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Resources/de.lproj/Localizable.strings
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Resources/en.lproj/Localizable.strings
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/BackgroundTaskCompletionWrapper.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/DisposalSelectionControl.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/IntrinsicTableView.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/PushSelectionControl.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux SampleTests/Multiplatform_Redux_SampleTests.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux SampleUITests/Multiplatform_Redux_SampleUITests.swift
  iOS/Multiplatform Redux Sample/Podfile
  iOS/Multiplatform Redux Sample/Podfile.lock
  iOS/Multiplatform Redux Sample/Pods/Local Podspecs/dreiKit.podspec.json
  iOS/Multiplatform Redux Sample/Pods/Local Podspecs/shared.podspec.json
  iOS/Multiplatform Redux Sample/Pods/Manifest.lock
  iOS/Multiplatform Redux Sample/Pods/Target Support Files/dreiKit/dreiKit-Info.plist
  iOS/Multiplatform Redux Sample/Pods/Target Support Files/shared/shared.debug.xcconfig
  iOS/Multiplatform Redux Sample/Pods/Target Support Files/shared/shared.release.xcconfig
  iOS/Multiplatform Redux Sample/Pods/dreiKit/Sources/dreiKit/String+Tools.swift
  iOS/Multiplatform Redux Sample/Pods/dreiKit/Sources/dreiKit/UIScrollView+ScrollTo.swift
  iOS/Multiplatform Redux Sample/fastlane/report.xml
  shared/src/androidMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/DriverFactory.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/AdditionalReminderDataStore.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/DatabaseHelper.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/Reminder.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/SettingsDataStore.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/actions/OpenedWithReminderNotification.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/thunk/NotificationThunks.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/thunk/Thunks.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/utils/LocalDateTime+now.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/utils/NotificationSnooze.kt
  shared/src/commonMain/sqldelight/ch/dreipol/multiplatform/reduxsample/shared/delight/V3__add_additionalReminders.sqm
  shared/src/commonMain/sqldelight/ch/dreipol/multiplatform/reduxsample/shared/delight/additionalReminder.sq
  shared/src/commonMain/sqldelight/ch/dreipol/multiplatform/reduxsample/shared/delight/disposal.sq
  shared/src/iosMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/DriverFactory.kt
  shared/src/iosMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/utils/FileReader.kt
Labels: ACK

#65 Feature/update swiftlint yml
  .swiftlint.yml
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/General/BasePresenterViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/BaseOnboardingViewController.swift
Labels: SCAN

#67 [fix_todo] Use values from enum rather then list them
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample.xcodeproj/project.pbxproj
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/MultiplatformExtensions/Array+KotlinInit.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/DisposalSelectionControl.swift
Labels: ACK, UNREVIEWED

#68 Feature/update dreidroid
  app/build.gradle
  app/src/main/java/ch/dreipol/rezhycle/view/CalendarListAdapter.kt
  build.gradle
Labels: ACK

#69 Feature/update dreimultiplatfrom
  build.gradle
Labels: ACK
