Repository dreipol/multiplatform-redux-sample, pull requests merged in 2021-01, with the labels that each got.

#6 Feature/licences
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/ch/dreipol/rezhycle/MainActivity.kt
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/styles.xml
  build.gradle
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/SettingsViewController.swift
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/MainScreen.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/actions/NavigationAction.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/reducer/NavigationReducer.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/SettingsView.kt
Labels: SCAN

#10 Feature/UI optimizations
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample.xcodeproj/project.pbxproj
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/BrandExtension/CALayer+Shadow.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/BrandExtension/HighlightableControl.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Dashboard/DisposalCell.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Dashboard/NextDisposalCell.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/General/Constants.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/General/PresenterViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/CalendarViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/SettingsViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/ToggleListItem.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/ZipCollectionViewCell.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Settings/NotificationSettingsViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Settings/SettingsEntryControl.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/UIColor+Brand.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/DisposalSelectionControl.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/HeaderView.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/PushSelectionControl.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/RoundDisposalImage.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/ZipEnterControl.swift
Labels: ACK

#13 [android_button_style] Use AppCompatButton to make background working
  app/src/main/res/layout/fragment_onboarding.xml
Labels: ACK, UNREVIEWED

#7 [onboarding_reducer_unit_tests] Add onboarding reducer tests
  shared/src/commonTest/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/OnboardingViewReducerTest.kt
Labels: ACK, UNREVIEWED

#11 [android_back_button] Align back icon
  app/src/main/res/layout/view_header.xml
Labels: ACK, UNREVIEWED

#12 [android_language_split] Disable language split
  app/build.gradle
Labels: ACK, UNREVIEWED

#14 [android_low_api] Enable java 8 features below api26
  app/build.gradle
Labels: ACK, UNREVIEWED

#15 Feature/android calendar lag
  app/src/main/java/ch/dreipol/rezhycle/fragments/CalendarFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/view/CalendarListAdapter.kt
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/view_calendar_header.xml
Labels: ACK

#17 [android_theme] Use material theme only for aboutlibraries
  app/src/main/java/ch/dreipol/rezhycle/MainActivity.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/LicenceFragment.kt
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/styles.xml
Labels: ACK

#21 Feature/ios improvements
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/General/PagePresenterViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/General/PresenterViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/MainCoordinator.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/SettingsViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/AddNotificationViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/BaseOnboardingViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/EnterZipViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/OnboardingCardViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/OnboardingFinishViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/SelectDisposalTypesViewController.swift
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/OnboardingView.kt
Labels: ACK, UNREVIEWED

#20 Feature/initilizable state
  app/src/main/java/ch/dreipol/rezhycle/MainActivity.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/MainFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/OnboardingNavigatorFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/view/NotificationListAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/SelectDisposalTypesAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/SelectItemListAdapter.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/AppState.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/ReduxSampleApp.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/Thunks.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/actions/SettingsInitializedAction.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/reducer/Reducers.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/ZipSettingsView.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/utils/AppLanguage.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/utils/SettingsHelper.kt
  shared/src/commonTest/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/InitialTestAppState.kt
  shared/src/commonTest/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/NavigationReducerTest.kt
Labels: SCAN, UNREVIEWED

#16 [readme_deployment] Edit release description
  README.md
Labels: ACK, UNREVIEWED

#22 Feature/android hide keyboard
  app/src/main/java/ch/dreipol/rezhycle/ReduxSampleActivity.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/BaseFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/EnterZipFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/OnboardingNavigatorFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/ZipSettingsFragment.kt
Labels: ACK
