Repository dreipol/multiplatform-redux-sample, pull requests merged in 2021-02, with the labels that each got.

#24 Feature/cargo icon
  app/src/main/res/drawable/ic_24_cargo_colored.xml
  app/src/main/res/drawable/ic_24_glas_colored.xml
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_cargo_colored.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_cargo_colored.imageset/icon_ic_24_cargo_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_glas_colored.imageset/iconIc24GlasColored.pdf
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/DisposalType.kt
Labels: ACK

#23 Feature/android accessibility
  app/src/main/java/ch/dreipol/rezhycle/fragments/BaseFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/CalendarFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/AddNotificationFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/FinishFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/OnboardingNavigatorFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/SelectDisposalTypesFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/CalendarSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/LanguageSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/NotificationSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/SettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/view/CalendarListAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/NextDisposalListAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/NotificationListAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/SelectDisposalTypesAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/SelectItemListAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/SettingsListAdapter.kt
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_navigator.xml
  app/src/main/res/layout/view_disposal_list_item.xml
  app/src/main/res/layout/view_header.xml
  app/src/main/res/layout/view_icon_list_item.xml
  app/src/main/res/layout/view_next_disposal_list_item.xml
  app/src/main/res/layout/view_toggle_list_item.xml
  app/src/main/res/menu/bottom_items.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/CalendarSettingsView.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/CalendarView.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/HeaderViewState.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/LanguageSettingsView.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/NotificationSettingsView.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/OnboardingView.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/SettingsView.kt
Labels: SCAN

#29 [android_language_switch] Update applanguage in appState
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/reducer/Reducers.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/thunk/Thunks.kt
Labels: ACK, UNREVIEWED

#30 [android_action_done] Set imeOptions for action done button on keyboard
  app/src/main/res/layout/view_enter_zip.xml
Labels: ACK

#32 [fix_header_height] Use header heights from design
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Dashboard/AllDisposalsDataSource.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/General/Constants.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/CalendarViewController.swift
Labels: ACK, UNREVIEWED

#27 [ios-inveractive_pop] Enable back swipe
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/General/PresenterViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/MainCoordinator.swift
Labels: FULL, UNREVIEWED

#31 [android_notifications] Set correct channel name
  app/src/main/java/ch/dreipol/rezhycle/utils/NotificationUtils.kt
Labels: ACK

#35 Feature/android new app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-hdpi/ic_launcher_beta_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-mdpi/ic_launcher_beta_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_beta_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_beta_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_beta_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: ACK

#38 [android_animation_update] Set new check color
  app/src/main/res/raw/check_animation.json
Labels: ACK, UNREVIEWED

#37 [new_icons] Update icos
  app/src/main/res/drawable/ic_24_bio_colored.xml
  app/src/main/res/drawable/ic_24_cargo_colored.xml
  app/src/main/res/drawable/ic_24_carton_colored.xml
  app/src/main/res/drawable/ic_24_cloth_colored.xml
  app/src/main/res/drawable/ic_24_electro_colored.xml
  app/src/main/res/drawable/ic_24_glas_colored.xml
  app/src/main/res/drawable/ic_24_oil_colored.xml
  app/src/main/res/drawable/ic_24_paper_colored.xml
  app/src/main/res/drawable/ic_24_tin_colored.xml
  app/src/main/res/drawable/ic_24_trash_colored.xml
Labels: ACK, UNREVIEWED

#33 [fix_safe_areas] Correct bottom margins for iPhone with iOS dock
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/BaseOnboardingViewController.swift
Labels: SCAN

#28 [adjust_fastlane] Rename setup_signing
  .gitignore
  iOS/Multiplatform Redux Sample/fastlane/Fastfile
  iOS/Multiplatform Redux Sample/fastlane/README.md
Labels: ACK

#39 Feature/ios redesign
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/AppIcon.appiconset/appIcon.png
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/AppIcon.appiconset/app_icon.png
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/AppIcon.appiconset/app_icon@2x.png
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/AppIcon.appiconset/app_icon@3x.png
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/AppIcon.appiconset/yourApp@2x.png
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/AppIcon.appiconset/yourApp@3x.png
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_bio_colored.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_bio_colored.imageset/icon_ic_24_bio_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_cargo_colored.imageset/icon_ic_24_cargo_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_carton_colored.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_carton_colored.imageset/iconIc24CartonColored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_carton_colored.imageset/icon_ic_24_carton_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_cloth_colored.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_cloth_colored.imageset/icon_ic_24_cloth_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_electro_colored.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_electro_colored.imageset/icon_ic_24_electro_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_notification_off.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_notification_off.imageset/icon_ic_24_notifications_off.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_notification_on.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_notification_on.imageset/icon_ic_24_notification_on.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_oil_colored.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_oil_colored.imageset/icon_ic_24_oil_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_paper_colored.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_paper_colored.imageset/icon_ic_24_paper_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_trash_colored.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_24_trash_colored.imageset/icon_ic_24_trash_colored.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_40_close_button.imageset/Contents.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Assets.xcassets/ic_40_close_button.imageset/icon_light_close_button.pdf
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/BrandExtension/CALayer+Shadow.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/BrandExtension/PrimaryButton.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/BrandExtension/UIImageView+Round.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/BrandExtension/UILabel+Brand.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Dashboard/AllDisposalsDataSource.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Dashboard/DisposalCell.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Dashboard/NextDisposalCell.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/InfoViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/MainViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/BaseOnboardingViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/OnboardingCardViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/ToggleListItem.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/ZipCollectionViewCell.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Resources/check_animation.json
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Settings/CalendarSettingsViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Settings/NotificationSettingsViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Settings/SettingsEntryControl.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Settings/ZipSettingsViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/UIColor+Brand.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/HeaderView.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/LinkableTextView.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/ZipEnterControl.swift
Labels: ACK

#36 Feature/android new colors
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/SelectDisposalTypesFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/CalendarSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/NotificationSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/ZipSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/utils/NotificationUtils.kt
  app/src/main/java/ch/dreipol/rezhycle/view/EnterZipView.kt
  app/src/main/java/ch/dreipol/rezhycle/view/NotificationListAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/SelectItemListAdapter.kt
  app/src/main/java/ch/dreipol/rezhycle/view/SettingsListAdapter.kt
  app/src/main/res/color/accent_color_state.xml
  app/src/main/res/color/accent_color_state_light.xml
  app/src/main/res/color/blue_clickable_background.xml
  app/src/main/res/color/blue_disabled_selector.xml
  app/src/main/res/color/bottom_icon_color.xml
  app/src/main/res/color/button_text_color_state.xml
  app/src/main/res/color/green_disabled_black_selector.xml
  app/src/main/res/color/green_disabled_blue_selector.xml
  app/src/main/res/color/primary_dark_color_state.xml
  app/src/main/res/color/secondary_color_state.xml
  app/src/main/res/color/secondary_light_color_state.xml
  app/src/main/res/color/transparent_clickable_background.xml
  app/src/main/res/color/white_color_state.xml
  app/src/main/res/color/white_disabled_selector.xml
  app/src/main/res/drawable/ic_24_notification_off.xml
  app/src/main/res/drawable/ic_24_notification_on.xml
  app/src/main/res/drawable/ic_36_check.xml
  app/src/main/res/drawable/ic_36_chevron_left.xml
  app/src/main/res/drawable/ic_40_close_button.xml
  app/src/main/res/drawable/primary_button_green.xml
  app/src/main/res/drawable/primary_dark_gradient.xml
  app/src/main/res/drawable/round_dark_background.xml
  app/src/main/res/drawable/round_dropdown_background.xml
  app/src/main/res/drawable/round_edit_text_background.xml
  app/src/main/res/drawable/round_icon_background.xml
  app/src/main/res/drawable/round_icon_background_transparent.xml
  app/src/main/res/drawable/round_white_background.xml
  app/src/main/res/font/open_sans_bold.ttf
  app/src/main/res/font/open_sans_semi_bold.ttf
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_calendar_settings.xml
  app/src/main/res/layout/fragment_info.xml
  app/src/main/res/layout/fragment_language_settings.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_notification_settings.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_navigator.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_zip_settings.xml
  app/src/main/res/layout/view_calendar_header.xml
  app/src/main/res/layout/view_disposal_group_item.xml
  app/src/main/res/layout/view_disposal_list_item.xml
  app/src/main/res/layout/view_dropdown_item.xml
  app/src/main/res/layout/view_enter_zip.xml
  app/src/main/res/layout/view_header.xml
  app/src/main/res/layout/view_icon_list_item.xml
  app/src/main/res/layout/view_next_disposal_list_item.xml
  app/src/main/res/layout/view_toggle_list_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: SCAN, UNREVIEWED

#40 Feature/touchdown effect
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Dashboard/DisposalCell.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/BaseOnboardingViewController.swift
Labels: ACK

#44 Fix notification tap in disposal list
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample.xcodeproj/project.pbxproj
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Dashboard/DisposalCell.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/General/NavigationCoordinator.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/CalendarViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/MultiplatformExtensions/Kermit+OSLogger.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/OnboardingCardViewController.swift
Labels: SCAN, UNREVIEWED

#51 Feature/ios map and zip
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/CollectionPointMapViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Resources/de.lproj/Localizable.strings
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Resources/en.lproj/Localizable.strings
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/ZipEnterControl.swift
Labels: ACK, UNREVIEWED

#46 Feature/touchdown effect
  app/src/main/java/ch/dreipol/rezhycle/fragments/BaseFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/OnboardingNavigatorFragment.kt
Labels: ACK, UNREVIEWED

#43 Feature/imprint
  app/src/main/java/ch/dreipol/rezhycle/MainActivity.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/ImprintFragment.kt
  app/src/main/res/layout/fragment_imprint.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample.xcodeproj/project.pbxproj
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/MainCoordinator.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Resources/de.lproj/Localizable.strings
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Resources/en.lproj/Localizable.strings
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Settings/ImprintViewController.swift
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/MainScreen.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/actions/NavigationAction.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/reducer/NavigationReducer.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/ImprintView.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/SettingsView.kt
Labels: ACK

#49 Feature/zip hint
  app/src/main/res/layout/view_enter_zip.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: ACK, UNREVIEWED

#54 [ios_zip_hint] Add hint for plz input view
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Utils/ZipEnterControl.swift
Labels: ACK, UNREVIEWED

#53 [ios_scrollbar] Hide vertical scrollbar indications
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Main/CalendarViewController.swift
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Onboarding/BaseOnboardingViewController.swift
Labels: ACK

#58 Feature/optimize localisation
  app/build.gradle
  shared/build.gradle
Labels: SCAN

#59 [android_language_switch] Make language switch working for devices below api 26
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/SettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/utils/LanguageUtils.kt
Labels: ACK, UNREVIEWED

#61 Feature/android systembar color
  app/src/main/java/ch/dreipol/rezhycle/fragments/BaseFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/LicenceFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/MainFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/onboarding/OnboardingNavigatorFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/CalendarSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/ImprintFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/LanguageSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/NotificationSettingsFragment.kt
  app/src/main/java/ch/dreipol/rezhycle/fragments/settings/ZipSettingsFragment.kt
Labels: ACK, UNREVIEWED

#57 Schedule notifications on a background thread
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample/Notifications/NotificationManager.swift
  shared/src/androidMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/AppState+Freeze.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/AppState.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/reducer/RootReducer.kt
  shared/src/iosMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/AppState+Freeze.kt
Labels: SCAN

#62 Feature/ios file reader
  iOS/Multiplatform Redux Sample/Multiplatform Redux Sample.xcodeproj/project.pbxproj
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/redux/reducer/RootReducer.kt
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/ui/CollectionPointMapView.kt
  shared/src/iosMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/utils/FileReader.kt
Labels: ACK, UNREVIEWED

#55 [enter_zip] Position cursor at the end of the text
  app/src/main/java/ch/dreipol/rezhycle/view/EnterZipView.kt
  app/src/main/res/layout/view_dropdown_item_disabled.xml
  app/src/main/res/layout/view_enter_zip.xml
Labels: ACK, UNREVIEWED

#63 Kotlin 1.4.31
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  shared/shared.podspec
  shared/src/commonMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/network/ServiceFactory.kt
Labels: SCAN, UNREVIEWED
